version: '3.7'

services:
  mysql: # A MySQL instance for the game server to use
    image: mysql:8.0
    restart: always
    networks:
      # Added the network bridge, so server and database can communicate
      front:
        ipv4_address: 127.0.0.1
    environment:
      # Configured the database credentials
      # Refer to https://hub.docker.com/_/mysql for more info.
      MYSQL_DATABASE: dodiannet
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3306:3306'
    volumes:
      # Where our data will be persisted
      - dev-db:/var/lib/mysql
      # Enable the below SQL file mappings if you want to initialize the database with data.
      # Do note that these files (the way they are done in this example) need to be in the same directory as this file.
      # You can find them in the "database"-directory of the game-server module
      # !! Everything depends on the mandatory_tables.sql, unless you took care of database another way
      #- ./mandatory_tables.sql:/docker-entrypoint-initdb.d/1_mandatory_game_tables.sql
      #- ./dodian_default_data.sql:/docker-entrypoint-initdb.d/2_dodian_default_data.sql
      #- ./convenient_data.sql:/docker-entrypoint-initdb.d/3_convenient_game_data.sql
      #- ./dummy_development_data.sql:/docker-entrypoint-initdb/4_dummy_game_data.sql

  game-server: # The Dodian game server (the "good" old Ub3r server)
    image: nozemi/ub3r-game-server:beta-1.0
    restart: unless-stopped
    networks:
      # Added the network bridge, so server and database can communicate
      front:
        ipv4_address: 172.16.238.20
    environment:
      # Required For a Valid Configuration (unless using config.json, which you shouldn't with this!)
      DATABASE_HOST: 172.16.238.10
      DATABASE_USERNAME: dodian
      DATABASE_PASSWORD: dodian_local_development_123

      # Optional Values - Set here for reference only
      # --- These optional values may be removed (or changed...)
      SERVER_NAME: Dodian
      SERVER_PORT: 43594

      DATABASE_NAME: dodiannet
      DATABASE_PORT: 3306
      DATABASE_TABLE_PREFIX: ''

      DEBUG_MODE: 'false'
      CLIENT_SECRET: NOT_SET
      MAX_CONNECTIONS_FROM_IP: 2
      WORLD_ID: 1
      EXPERIENCE_MULTIPLIER: 1
      CUSTOM_CLIENT_VERSION: ''
    ports:
      - '43594:43594'

volumes:
  dev-db:

# Defined a bridge network for the server and database containers to communicate within
networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1